### ISSUE TITLE
Documented step to sign image with key is not working

### ISSUE THREAD

**Issue by dhaus67** [sigstore/cosign-installer#73]
**Description**

When setting up the action, using the key pair to generate the signtature of a docker image, the documented step is:
```yaml
      - name: Sign image with a key
        run: |
          echo ${COSIGN_KEY} > /tmp/my_cosign.key && \
          cosign sign --key /tmp/my_cosign.key ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
```

Now, when creating a repository secret containing the private key and trying to sign the image, the following error was returned:
```
Run echo $COSIGN_KEY > cosign.key && \
Error: signing [<some-image>[12](<action-link>)35220bf96fc87504ec76d37774]: getting signer: reading key: invalid pem block
main.go:46: error during command execution: signing [<some-image>]: getting signer: reading key: invalid pem block
```

What fixed the issue for me was to create a step before which writes the secret to a file and use that file within `cosign sign`:
```yaml
      - name: Write cosign private key to file
        env:
         KEY: ${{ secrets.COSIGN_KEY }}
        shell: bash
        run: 'echo "$KEY" > cosign.key'

      - name: Sign image with a key
        run: |
          cosign sign --key cosign.key ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
```

I'm not sure whether there's a better solution to fix this or a mistake I did, but it feels as if the documentation is wrong for the key example.

**Comment by eumel8** [comment]
@dhaus67 thx, works!

**Comment by cpanato** [comment]
you also can do the following and remove the step that create the file

```
      - name: Sign image with a key
        run: |
          cosign sign --key env://COSIGN_KEY ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
```
