### ISSUE TITLE
Error: Fail to load sigstore/cosign-installer/v2.0.0/action.yml

### ISSUE THREAD

**Issue by UrsusLvovich** [sigstore/cosign-installer#77]
cosign-installer version: v2.0.0

When trying to use this version, the github action will sometimes fail on start up, and sometimes it'll pass the start up and proceed as expected. 

Here's the code snippet of where I'm using the cosign installer:
![image](https://user-images.githubusercontent.com/38516315/169341305-9f59b1d2-8008-42b9-b684-99c3a86f91cf.png)

Here is the error I'm getting:
![image](https://user-images.githubusercontent.com/38516315/169340734-01e38101-a1ae-4bf8-81c7-7666d4005c95.png)

Would this be an issue with v2.0.0? Would using the latest version fix these intermittent failures?
It's hard to know exactly how often it fails, but seems to be one in every 5 or so builds.

**Comment by cpanato** [comment]
please use release v2.3.0

i will try to reproduce this issue, but i would say to use the latest version and if that persist the error we need to investigate deeper

**Comment by UrsusLvovich** [comment]
We tried to use the latest version but still got the error

**Comment by cpanato** [comment]
is it possible point me to your github action workflow?

**Comment by UrsusLvovich** [comment]
our github action is on our company's github network. So I won't be able to point you directly to it.
The github actions are running on github hosted runners, with ubuntu-latest

**Comment by UrsusLvovich** [comment]
Have you been able to re-produce the error on your end? We're still experiencing intermittent issues with this github action

**Comment by cpanato** [comment]
@UrsusLvovich unfortunately not, we use this action across several projects and I never saw this error, and with the information you provide is kind of hard to debug.

things I would like to know:
1 - it is using a public GitHub runner? or private (this might have a possible impact)
2 - the action yaml definition (i know that you cannot share)
3 - which ubuntu version you are using


also please update to the latest action which is `v2.4.0`

**Comment by UrsusLvovich** [comment]
1. We're using a github hosted runner
2. The action.yaml file is below
3. The runner is using ubuntu-latest

```yaml
---
name: Deploy Images

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "**"
jobs:
  push-images:
    name: Push Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.9
      - name: Install Task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
      - name: Build Images
        run: |
          task
      - name: |
        run: |
          host [REDACTED]
      - name: Login to Docker
        run: |
          echo ${{ secrets.HARBOR_REGISTRY_TOKEN }} | docker -D -ldebug login --username ${{ secrets.HARBOR_USERNAME }} [REDACTED] --password-stdin
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract tag name
        if: contains(steps.extract_branch.outputs.branch, 'tags/release')
        run: echo "##[set-output name=tag;]$(echo ${{ steps.extract_branch.outputs.branch }} | cut -d '/' -f4)"
        id: extract_tag
      - name: Set tag name
        id: tag
        shell: bash
        run: |
          if [ "${{ steps.extract_tag.outputs.tag }}" != "" ]; then
            echo ::set-output name=name::${{ steps.extract_tag.outputs.tag }}
          else
            echo ::set-output name=name::${{ steps.extract_branch.outputs.branch }}
          fi
      - name: Install cosign
        uses: sigstore/cosign-installer@v2.3.0
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      - name: Tag, push and sign cds/pipeline
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          docker tag cds/pipeline:latest [REDACTED]/cds/pipeline:${{ steps.tag.outputs.name }}
          docker push [REDACTED]/cds/pipeline:${{ steps.tag.outputs.name }}
          cosign sign --key cosign.key [REDACTED]/cds/pipeline:${{ steps.tag.outputs.name }}

```

**Comment by cpanato** [comment]
thanks!
i've configure a self-runner (`linux debian-11-bullseye-v20220519`on GCP) using this repo https://github.com/actions/runner/

logs from the runner
```

√ Connected to GitHub

Current runner version: '2.293.0'
2022-06-16 09:54:00Z: Listening for Jobs
2022-06-16 09:54:10Z: Running job: build
2022-06-16 09:54:20Z: Job build completed with result: Succeeded
```

sample job
```
name: cosign with key
on:
  workflow_dispatch:


jobs:
  build:
    permissions:
      packages: write
      contents: read

    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install cosign
        uses: sigstore/cosign-installer@v2.4.0

      - name: Install crane
        uses: imjasonh/setup-crane@v0.1

      - name: Build and sign a container image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ghcr.io/cpanato/testing-ci-providers/test:latest
```

link for the execution: https://github.com/cpanato/testing-ci-providers/runs/6916203906?check_suite_focus=true 
i've run that a few times and always worked
